config/routes.rb
Livestock::Application.routes.draw do

  resources :notes
  resources :animals do
    collection do
      get 'close'
    end
  end
  resources :users
  resources :owners
  resources :matings,     only: [:new, :create, :destroy]
  resources :sessions,    only: [:new, :create, :destroy]

  root  to: 'static_pages#home'
  get       "static_pages/home"
  match '/help'    => 'static_pages#help'
  match '/about'   => 'static_pages#about'
  match '/no_owner'=> 'static_pages#no_owner'
  match '/signup'  => 'users#new'
  match '/signin'  => 'sessions#new'
  match '/signout' => 'sessions#destroy', via: :delete

end

app/models/owner.rb
# == Schema Information
#
# Table name: owners
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  pnum       :string(255)
#  orgnum     :string(255)
#  prodnum    :string(255)
#

class Owner < ActiveRecord::Base
  attr_accessible :email, :name, :pnum, :orgnum, :prodnum

  has_many :animals
  has_many :notes
  has_and_belongs_to_many :users

  validates :email, :presence => true
  validates :name, :presence => true

  def living_animals
    animals.where(death_date: nil)
  end

  def female_animals
    living_animals.where(sex: 'female')
  end

  def male_animals
    living_animals.where(sex: 'male')
  end

  def user
    users.first
  end

  def user=(user)
    set_user(user)
  end

  def set_user(user)
    users.delete(user)
    other_users = users.all
    users.delete_all
    users << user
    users << other_users
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  include OwnersHelper
  before_filter :signed_in_user, :current_user_has_owner

  # GET /owners/1
  # GET /owners/1.json
  def show
    @owner = Owner.find(params[:id])

    respond_to do |format|
      format.html
      format.js
      format.json { render json: @owner}
    end
  end

  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @owners }
    end
  end

  def create
    @owner = Owner.new(params[:owner])
    if @owner.save
      flash[:success] = "Owner created"
      redirect_to @owner
    else
      render 'new'
    end
  end

  def new
    @owner = Owner.new
  end

  def edit
    @owner = Owner.find(params[:id])
  end

  def update
    @owner = Owner.find(params[:id])
    if User.exists?(params[:user])
      @user = User.find(params[:user])
      if params[:Add] == 'true'
        @owner.user = @user
      else
        @owner.users.delete(@user)
      end
    end
    if @owner.update_attributes(params[:owner])
      flash[:success] = "Owner updated"
    else
      flash[:error] = "Owner was not updated"
    end
    redirect_to @owner
  end

  def destroy
    Owner.find(params[:id]).destroy
    flash[:success] = "Owner is deleted"
    redirect_to owners_url
  end
end

app/helpers/owners_helper.rb
module OwnersHelper
  include UsersHelper

  def current_user_has_owner
    unless user_has_owner?(current_user)
      flash.now[:notice] = 'No owner is assosiated with this user'
    end

  end
end

app/views/owners/_form.html.erb
<%= form_for(@owner, :html => { :class => "form-horizontal"} ) do |f| %>
    <% if @owner.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

          <ul>
            <% @owner.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="control-group">
      <%= f.label :name, class: "control-label" %>
      <div class="controls">
        <%= f.text_field :name %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :email, class: "control-label" %>
      <div class="controls">
        <%= f.email_field :email %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label "Person number", class: "control-label" %>
      <div class="controls">
        <%= f.text_field :pnum %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label "Organisation number", class: "control-label" %>
      <div class="controls">
        <%= f.text_field :orgnum %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label "Manufacturer number", class: "control-label" %>
      <div class="controls">
        <%= f.text_field :prodnum %>
      </div>
    </div>
    <div class="actions">
      <%= f.submit yield(:SaveLabel), class: "btn btn-large btn-primary" %>
      <%= link_to 'Close', owners_path, class: "btn btn-large btn-primary" %>
    </div>
<% end %>

app/views/owners/edit.html.erb
<% provide(:title, "Edit "+@owner.name) %>
<h1>Update owner profile</h1>

<% provide(:SaveLabel, "Update Owner") %>
<%= render 'form' %>

app/views/owners/index.html.erb
<%= provide(:title, 'All owners') %>
<h1>Registered owners in database</h1>
<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% @owners.each do |owner| %>
  <tr>
    <td><%= owner.name %></td>
    <td><%= owner.email %></td>
    <td></td>
    <td></td>
    <td></td>
    <td><%= link_to 'Show', owner, class: 'btn' %></td>
    <td><%= link_to 'Edit', edit_owner_path(owner), class: 'btn' %></td>
    <td><%= link_to 'Delete', owner, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn' %></td>
  </tr>
  <% end %>
</table>
<br />
<%= link_to 'New Owner', new_owner_path, :class=>'new_owner btn btn-large btn-primary' %>

app/views/owners/new.html.erb
<% provide(:title, "Create owner") %>
<h1>Create new profile</h1>

<% provide(:SaveLabel, "Create Owner") %>
<%= render 'form' %>

app/views/owners/show.html.erb
<% provide(:title, @owner.name) %>
<h1><%= @owner.name %></h1>
<ul>
  <li>Email: <%= @owner.email %></li>
  <li>OrgNum: <%= @owner.orgnum %></li>
  <li>PNum: <%= @owner.pnum %></li>
  <li>Prod number: <%= @owner.prodnum %></li>
  <li>Total number of animals: <%= @owner.living_animals.count %></li>
  <li>Users: <%= @owner.users.count %></li>
  <ul>
    <% @owner.users.each do |user| %>
    <li><%=  user.name %>, <%= user.email %></li>
    <% end %>
  </ul>
</ul>
<%= link_to 'Edit', edit_owner_path(@owner), class: "btn btn-large btn-primary" %>
<%= link_to 'Close', owners_path, class: "btn btn-large btn-primary" %>
<br/>
<br/>
<%= form_for(@owner) do |f| %>
    <%= hidden_field_tag :user, current_user.id %>
    <% if @owner.users.exists?(current_user) %>
        <%= hidden_field_tag :Add, false %>
        <%= f.submit 'Remove me from this owner', class: "btn btn-large btn-primary" %>
    <% else %>
        <%= hidden_field_tag :Add, true %>
        <%= f.submit 'Add me to this owner', class: "btn btn-large btn-primary" %>
    <% end %>
<% end %>