config/routes.rb
Livestock::Application.routes.draw do

  resources :notes
  resources :animals do
    collection do
      get 'close'
    end
  end
  resources :users
  resources :owners
  resources :matings,     only: [:new, :create, :destroy]
  resources :sessions,    only: [:new, :create, :destroy]

  root  to: 'static_pages#home'
  get       "static_pages/home"
  match '/help'    => 'static_pages#help'
  match '/about'   => 'static_pages#about'
  match '/no_owner'=> 'static_pages#no_owner'
  match '/signup'  => 'users#new'
  match '/signin'  => 'sessions#new'
  match '/signout' => 'sessions#destroy', via: :delete

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#  remember_token  :string(255)
#  admin           :boolean
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password

  has_and_belongs_to_many :owners

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  validates :name, :presence => true, :length => { :maximum => 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, :presence => true, :format => { :with => VALID_EMAIL_REGEX },
            :uniqueness => { :case_sensitive => false }
  validates :password, :presence => true, :length => { :minimum => 6 }
  validates :password_confirmation, :presence => true

  def owner
    owners.first
  end

  def owner=(owner)
    set_owner(owner)
  end

  def set_owner(owner)
    unless owner.nil?
      owners.delete(owner)
      other_owners = owners.all
      owners.delete_all
      owners << owner
      owners << other_owners
    end
  end

  private
  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update, :index,
                                        :destroy, :following, :followers]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :admin_user,     only: :destroy

  def show
    @user = User.find(params[:id])
    @owners_any = Owner.any?
  end

  def new
    @user = User.new
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Brukar er sletta."
    redirect_to users_url
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Velkomen til husdyrdatabasen!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile oppdatert"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    @users = User.paginate(page: params[:page])
  end


  private
  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_has_owner?(user)
    !user.owner.nil?
  end
end

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
    <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
  <div class="span6 offset3">
    <%=  form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation %>

        <%=  f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= @user.name %>
      </h1>
      <ul>
        <li>E-mail: <%= @user.email %></li>
      </ul>
      <%= link_to('Edit', edit_user_path, class: 'btn btn-large btn-primary') %>
      <br/>
    </section>
    <section>
      <% if @user.owners.any? %>
        <h3>Assosiated owner</h3>
        <%= link_to(@user.owner.name, owner_path(@user.owner), class: 'btn btn-primary') %>
        <%= link_to('Owners', owners_path, class: 'btn btn-primary') %>
      <% else %>
        <h3>No owners assosiated with user</h3>
        <%= link_to('Create Owner', new_owner_path, class: 'btn btn-primary') %>
        <% if @owners_any %>
          <%= link_to('Owners', owners_path, class: 'btn btn-primary') %>
        <% end %>
      <% end %>
    </section>
  </aside>
</div>