config/routes.rb
Livestock::Application.routes.draw do

  resources :notes
  resources :animals do
    collection do
      get 'close'
    end
  end
  resources :users
  resources :owners
  resources :matings,     only: [:new, :create, :destroy]
  resources :sessions,    only: [:new, :create, :destroy]

  root  to: 'static_pages#home'
  get       "static_pages/home"
  match '/help'    => 'static_pages#help'
  match '/about'   => 'static_pages#about'
  match '/no_owner'=> 'static_pages#no_owner'
  match '/signup'  => 'users#new'
  match '/signin'  => 'sessions#new'
  match '/signout' => 'sessions#destroy', via: :delete

end

app/models/animal.rb
# == Schema Information
#
# Table name: animals
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  id_tag     :string(255)
#  birth_date :date
#  death_date :date
#  sex        :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  father_id  :integer
#  mother_id  :integer
#  owner_id   :integer
#

require 'date'

class Animal < ActiveRecord::Base
  attr_accessible :birth_date, :death_date, :id_tag, :name, :sex, :mother_id, :father_id
  enum_attr :sex, %w(male female)
  belongs_to :owner
  belongs_to :mother, :class_name => 'Animal'#, :foreign_key => 'mother_id'
  belongs_to :father, :class_name => 'Animal'#, :foreign_key => 'father_id'
  has_many :children, :class_name => 'Animal', :foreign_key => 'mother_id'
  has_and_belongs_to_many :notes
  has_many :matings

  def year
    birth_date.year
  end

  def add_mating(date, uncertainty = 1)
    if sex.eql?(:female) then
      matings.create(mating_date: date, uncertainty: uncertainty)
    end
  end

  validates :id_tag, presence: true
  validates :sex, presence: true
  validates :birth_date, presence: true
  validate :validate_birth_date

  before_validation :update_parents
  
  private
    def update_parents
      self.mother = Animal.find(@mother_id) if @mother_id
      self.father = Animal.find(@father_id) if @father_id
    end

    def validate_birth_date
      if !birth_date.blank? and birth_date.future?
        errors.add(:birth_date, "is in the future!")
      end
    end
    
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  include AnimalsHelper
  before_filter :signed_in_user, :current_user_has_owner
  # GET /animals
  # GET /animals.json
  def index
    @animals = get_animals_for_pagination(params[:year])
    @years = get_years_in_stock_for_current_user
    respond_to do |format|
      format.html { render locals: {selected_year: params[:year]}}
      format.json { render :json => @animals }
    end
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
    @animal = Animal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.js
      format.json { render :json => @animal }
    end
  end

  # GET /animals/close
  def close
    respond_to do |format|
      format.js
    end
  end

  # GET /animals/new
  # GET /animals/new.json
  def new
    @animal = Animal.new
    @animal.owner = current_user.owners.first
    respond_to do |format|
      format.js
      format.html # new.html.erb
      format.json { render :json => @animal }
    end
  end

  # GET /animals/1/edit
  def edit
    @animal = Animal.find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.new(params[:animal])
    @animal.owner = current_user.owners.first
    @animals = get_animals_for_pagination(@animal.birth_date.year.to_s)
    @years = get_years_in_stock_for_current_user

    respond_to do |format|
      if @animal.save
        flash[:notice] = 'Animal was successfully created.'
        format.html { redirect_to @animal, remote: true, :class=>'show_animal' }
        format.json { render :json => @animal, :status => :created, :location => @animal }
        format.js
      else
        format.html { render :action => "new" }
        format.json { render :json => @animal.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /animals/1
  # PUT /animals/1.json
  def update
    @animal = Animal.find(params[:id])
    @animal.assign_attributes(params[:animal])
    @animals = get_animals_for_pagination(@animal.birth_date.year.to_s)
    @years = get_years_in_stock_for_current_user

    respond_to do |format|
      if @animal.save
        flash[:notice] = 'Animal was successfully updated.'
        format.html { redirect_to @animal, :remote=>true, :class=>'show_animal' }
        format.json { render :json => @animal, :status => :updated, :location => @animal }
        format.js
      else
        format.html { render :action => "edit" }
        format.json { render :json => @animal.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal = Animal.find(params[:id])
    @animals = get_animals_for_pagination(@animal.birth_date.year.to_s)
    animal_id = @animal.id_tag
    @animal.destroy
    @years = get_years_in_stock_for_current_user


    respond_to do |format|
      flash[:notice] = 'Animal '+ animal_id +' was deleted.'
      format.html { redirect_to animals_url, remote: true}
      format.json { head :no_content }
      format.js
    end
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
  include UsersHelper
  include SessionsHelper
  def add_matingdate(animal)
  end

  def current_user_has_owner
    unless user_has_owner?(current_user)
      redirect_to no_owner_url, notice: "Please assosiate a owner to this user."
    end
  end

  def get_animals_for_pagination(year)
    start_year = Date.parse('1.1.1970')
    end_year = Date.today
    if year.present? then
      start_year = Date.parse('1.1.' + year)
      end_year = Date.parse('31.12.' + year)
    end

    current_user.owner.animals.where("birth_date >= ? and birth_date <= ?",
           start_year,end_year).paginate(page: params[:page])
  end

  def get_years_in_stock(owner)
    years = []
    for animal in owner.living_animals do
      if not years.include? animal.birth_date.year then
        years << animal.birth_date.year
      end
    end
    years
  end

  def get_years_in_stock_for_current_user
    get_years_in_stock(current_user.owner)
  end
end

app/views/animals/_edit.html.erb
<h1>Rediger Dyr</h1>

<%= render 'form' %>
<%= link_to 'Vis', @animal, :remote=>true, :class=>'show_animal btn btn-large btn-primary' %>

app/views/animals/_form.html.erb
<%= form_for(@animal, remote:true, :html => { :class => "form-horizontal"} ) do |f| %>
  <% if @animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
      <% @animal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :Namn, class: "control-label" %>
    <div class="controls">
        <%= f.text_field :name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :Id_merke, class: "control-label" %>
    <div class="controls">
        <%= f.text_field :id_tag %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :Fødselsdato, class: "control-label" %>
    <div class="controls">
        <%= f.text_field :birth_date, 'data-behaviour' => 'datepicker' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :kjønn, class: "control-label" %>
    <div class="controls">
        <%= f.enum_select :sex %>
    </div>
  </div>
 
  <div class="control-group">
    <%= f.label :Mor, class: "control-label" %>
    <div class="controls">
        <%= f.collection_select(:mother_id, @animal.owner.female_animals, :id, :id_tag, {:prompt => true}) %>
    </div>
 </div>
 <div class="control-group">
   <%= f.label :Far, class: "control-label" %>
   <div class="controls">
      <%= f.collection_select(:father_id, @animal.owner.male_animals, :id, :id_tag, {:prompt => true}) %>
   </div>
 </div>

  <div class="actions">
    <%= f.submit "Lagre", class: "btn btn-large btn-primary" %>
    <%= link_to 'Lukk', 'animals/close', :remote=>true, class: "btn btn-large btn-primary" %>
  </div>
<% end %>

app/views/animals/_list.html.erb
<h1>Husdyroversikt</h1>
<% unless @years.nil? then %>
<ul class='nav nav-tabs'>
  <% @years.each do |year| %>
    <% unless selected_year.nil? %>
        <% if year.to_s.eql?(selected_year.to_s)%>
          <li class="active">
        <% else %>
          <li>
        <% end %>
    <% else %>
        <li>
    <% end %>
    <%= link_to year, animals_path(year: year) %></li>
  <% end %>
</ul>
<% end %>
<table class="table table-hover">
  <thead>
      <tr>
        <th>Kjennemerke</th>
        <th>Namn</th>
        <th>Fødselsdato</th>
        <th>Kjønn</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
  </thead>
  <tbody>
      <%= will_paginate %>
      <% @animals.each do |animal| %>
          <tr id="animal_<%= animal.id.to_s %>">
            <td><%= animal.id_tag %></td>
            <td><%= animal.name %></td>
            <td><%= animal.birth_date %></td>
            <td><%= animal.sex %></td>
            <td><%= link_to 'Vis', animal, :remote=>true, :class=>'show_animal'  %></td>
            <td><%= link_to 'Rediger', edit_animal_path(animal), :remote=>true, :class=>'edit_animal' %></td>
            <td><%= link_to 'Slett', animal, remote: true, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
          </tr>
      <% end %>
  </tbody>
</table>
<%= will_paginate %>

<br />

<%= link_to 'Nytt dyr', new_animal_path, :remote=>true, :class=>'new_animal btn btn-large btn-primary' %>

app/views/animals/_new.html.erb
<h1>Nytt dyr</h1>

<%= render 'form' %>

app/views/animals/_show.html.erb
<div id="livestock-show-animal">
  <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
  <% end %>
  <% if @animal.sex = "female" %>
    <h1>Søye <%= @animal.id_tag %></h1>
  <% else %>
    <h1>Vær <%= @animal.id_tag %></h1>
  <% end %>
  <p class="notice"><%= notice %></p>

  <p>
    <b>Namn:</b>
    <%= @animal.name %>
  </p>

  <p>
    <b>Fødselsdato:</b>
    <%= @animal.birth_date %>
  </p>

  <p>
    <b>Kjønn:</b>
    <%= @animal.sex %>
  </p>

  <% if @animal.mother %>
  <p>
    <b>Mor:</b>
    <%= @animal.mother.id_tag %>
    <%= @animal.mother.name %>
  </p>
  <% end %>

  <% if @animal.father %>
  <p>
    <b>Far:</b>
    <%= @animal.father.id_tag %>
    <%= @animal.father.name %>
  </p>
  <% end %>

  <% if not @animal.children.blank? %>
  <p>
    <b>Lam:</b>
    <ul>
    <% @animal.children.each do |child| %>
      <li><%= child.name %> <%= child.id_tag %></li>
    <% end %>
    </ul>
  <% end %>
  </p>
  <hr>
  <h2>Meldingar</h2>
  <p>
    <table>
    <% @animal.notes.each do |message| %>
      <tr>
	<td><%= message.date_from %></td>
	<td><%= message.note %></td>
      </tr>
    <% end %>
    </table>
  </p>

  <%= link_to 'Legg til paringsdato', new_mating_path(animal: @animal), :class=>"edit_animal btn btn-large btn-primary" %>
  <%= link_to 'Rediger', edit_animal_path(@animal), :remote=>true, :class=>"edit_animal btn btn-large btn-primary"  %>
  <%= link_to 'Lukk', 'animals/close', :remote=>true, class: "btn btn-large btn-primary"  %>
</div>

app/views/animals/close.js.erb
$('#display-details').html('');

app/views/animals/create.js.erb
$('#display-details').html("<%= escape_javascript(render :partial => 'animals/show') %>");
$('#animal-list').html("<%= escape_javascript(render :partial => 'animals/list') %>");

app/views/animals/destroy.js.erb
$('#display-details').html("");
$('#animal-list').html("<%= escape_javascript(render :partial => 'animals/list') %>");

app/views/animals/edit.js.erb
$('#display-details').html("<%= escape_javascript(render :partial => 'animals/edit') %>");

app/views/animals/index.html.erb
<div class="row">
  <div id="animal-list"  class="span6">
    <%=  render 'list', selected_year: local_assigns[:selected_year]  %>
  </div>
  <div id="display-details" class="span6">
  </div>
</div>

app/views/animals/index.js.erb
$('#animal-list').html("<%= escape_javascript(render :partial => 'animals/list') %>");

app/views/animals/new.js.erb
$('#display-details').html("<%= escape_javascript(render :partial => 'animals/new') %>");

app/views/animals/show.html.erb
<%= render 'show' %>

app/views/animals/update.js.erb
$('#display-details').html("<%= escape_javascript(render :partial => 'animals/show') %>");
$('#animal-list').html("<%= escape_javascript(render :partial => 'animals/list') %>");