config/routes.rb
Livestock::Application.routes.draw do

  resources :notes
  resources :animals do
    collection do
      get 'close'
    end
  end
  resources :users
  resources :owners
  resources :matings,     only: [:new, :create, :destroy]
  resources :sessions,    only: [:new, :create, :destroy]

  root  to: 'static_pages#home'
  get       "static_pages/home"
  match '/help'    => 'static_pages#help'
  match '/about'   => 'static_pages#about'
  match '/no_owner'=> 'static_pages#no_owner'
  match '/signup'  => 'users#new'
  match '/signin'  => 'sessions#new'
  match '/signout' => 'sessions#destroy', via: :delete

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Husdyrdatabase", "#", id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Heim", root_path %></li>
          <li><%= link_to "Hjelp", help_path %></li>
          <li><%= link_to "Husdyr", animals_path %></li>
          <li><%= link_to "Om", about_path %></li>
          <% if signed_in? %>
            <li><%= link_to current_user.name, current_user  %></li>
            <li><%= link_to "Logg ut", signout_path, method: "delete" %></li>
          <% else %>
            <li><%= link_to "Logg inn" , signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>